// Code generated by "stringer -type VersionType,ErasureAlgo -output=xl-storage-format-v2_string.go xl-storage-format-v2.go"; DO NOT EDIT.

package cmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[invalidVersionType-0]
	_ = x[ObjectType-1]
	_ = x[DeleteType-2]
	_ = x[lastVersionType-4]
}

const (
	_VersionType_name_0 = "invalidVersionTypeObjectTypeDeleteType"
	_VersionType_name_1 = "lastVersionType"
)

var (
	_VersionType_index_0 = [...]uint8{0, 18, 28, 38}
)

func (i VersionType) String() string {
	switch {
	case i <= 2:
		return _VersionType_name_0[_VersionType_index_0[i]:_VersionType_index_0[i+1]]
	case i == 4:
		return _VersionType_name_1
	default:
		return "VersionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[invalidErasureAlgo-0]
	_ = x[ReedSolomon-1]
	_ = x[lastErasureAlgo-2]
}

const _ErasureAlgo_name = "invalidErasureAlgoReedSolomonlastErasureAlgo"

var _ErasureAlgo_index = [...]uint8{0, 18, 29, 44}

func (i ErasureAlgo) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ErasureAlgo_index)-1 {
		return "ErasureAlgo(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErasureAlgo_name[_ErasureAlgo_index[idx]:_ErasureAlgo_index[idx+1]]
}
